"""Constants for the JEBAO MDC integration."""

DOMAIN = "jebao_mdc"

CONF_PASSCODE = "passcode"
CONF_DEVICE_ID = "device_id"
CONF_MAC = "mac"
CONF_NORMAL_SETPOINT = "normal_setpoint"
CONF_FEEDING_SETPOINT = "feeding_setpoint"
CONF_FEEDING_DURATION = "feeding_duration"
CONF_FEEDING_UNTIL = "feeding_until"

DEFAULT_DISCOVERY_PORT = 12414
DEFAULT_PORT = 12416
DEFAULT_PASSCODE = ""
DEFAULT_NORMAL_SETPOINT = 57
DEFAULT_FEEDING_SETPOINT = 30
DEFAULT_FEEDING_DURATION = 10

MANUFACTURER = "JEBAO"
MODEL = "MDC"
